#MYSQLServer     localhost
#MYSQLPort       3306
MYSQLSocket     /home/isp/apps/mysql/mysql.sock
MYSQLUser       root
MYSQLPassword   comeongogogo
MYSQLDatabase   isp
MYSQLCrypt      cleartext
MYSQLGetPW	SELECT u.ftp_user_password as passwd FROM isp_domain d join isp_ftp_user u on d.no=u.ftp_user_domain_no WHERE u.ftp_user_name="\L" and d.host_service=1
MYSQLGetUID     SELECT 1000
MYSQLGetGID     SELECT 1000
MYSQLGetDir	SELECT concat('/home/isp/hosts/',d.ftp_dir,'/',u.ftp_user_path) from isp_domain d join isp_ftp_user u on d.no=u.ftp_user_domain_no WHERE u.ftp_user_name="\L"
#MYSQLGetDir     SELECT concat('/home/isp/hosts/',domain_name,'/') from isp_domain WHERE domain_name="\L" 
#MYSQLGetDir     SELECT concat('/home/isp/hosts/',ftp_dir,'/') from isp_domain WHERE domain_name="\L" 
