server
{
  listen 80;

  server_name oa.wydiy.com;
  access_log /usr/logs/oa.wydiy.com.log main;
  index index.html index.htm;
  root /home/oa/webapps/hostroot/oa.wydiy.com/;
  
  location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
  {
    expires      30d;
  }

  location ~ .*\.(js|css)?$
  {
    expires      1h;
  }
}

