server
  {
    listen 443 ssl http2;
    listen 80;

    ssl_certificate /home/oa/apps/nginx/ca/server/server.crt;
    ssl_certificate_key /home/oa/apps/nginx/ca/server/server.key;
    ssl_prefer_server_ciphers on;

    error_page 497  https://$host$uri?$args;
    error_page 404  https://$host$uri?$args;

    server_name pms.wydiy.com;
    index index.html index.htm index.php;
    root /home/oa/webapps/hostroot/pms.wydiy.com/;

    location ~ .*\.(php|php5)?$
    {
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      include fastcgi.conf;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
      expires      30d;
    }

    location ~ .*\.(js|css)?$
    {
      expires      1h;
    }

        access_log /usr/logs/pms.wydiy.com.log main;
  }

