server
  {
    listen 443 ssl http2;
    listen 80;
    charset utf-8;

    ssl_certificate /home/oa/apps/nginx/ca/server/server.crt;
    ssl_certificate_key /home/oa/apps/nginx/ca/server/server.key;
    ssl_prefer_server_ciphers on;

    error_page 497  https://$host$uri?$args;
    error_page 404  https://$host$uri?$args;

    server_name webdav.wydiy.com;

    location / {
      dav_methods PUT DELETE MKCOL COPY MOVE;
      dav_ext_methods PROPFIND OPTIONS;
      dav_access user:rw group:r all:r;
      create_full_put_path on;
      root /home/oa/doc;
      autoindex on;
      auth_ldap "Forbidden";
      auth_ldap_servers openldap;
    }

    access_log /usr/logs/webdav.wydiy.com.log main;
  }

